---
name: Bug Report
about: Create a report to help us improve
title: '[Bug]: '
labels: ['bug', 'needs triage']
assignees: ''
---

## Bug Description

A clear and concise description of what the bug is.

## To Reproduce

Steps to reproduce the behavior:

1. Install version '...'
2. Configure with '...'
3. Run command '...'
4. See error

## Expected Behavior

A clear and concise description of what you expected to happen.

## Actual Behavior

What actually happened instead.

## Environment

- **next-llms-txt version**: [e.g., 1.0.0]
- **Next.js version**: [e.g., 16.0.1]
- **Node.js version**: [e.g., 22.0.0]
- **Package manager**: [e.g., npm, yarn, pnpm, bun]
- **Operating System**: [e.g., macOS, Windows, Linux]

## Configuration

```typescript
// Your createLLmsTxt configuration
export const { GET } = createLLmsTxt({
  // ... your config
});
```

## Error Messages

```
Paste any error messages or logs here
```

## Additional Context

Add any other context about the problem here. Screenshots, code snippets, or links to reproduction repositories are helpful.

## Possible Solution

If you have suggestions on how to fix the bug, please describe them here.
