version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    open-pull-requests-limit: 10
    reviewers:
      - "bke-daniel"
    assignees:
      - "bke-daniel"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group all minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
    labels:
      - "github-actions"
      - "automated"
    ignore:
      # Ignoriere alles unter 24
      - dependency-name: "@types/node"
        versions: ["<24.0.0"]

      # Ignoriere alles ab 25
      - dependency-name: "@types/node"
        versions: [">=25.0.0"]
